version: "3.9"
services:
  projects-bot-postgres:
    image: postgres:13 #13
    environment:
      POSTGRES_DB: "projects_bot_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d projects_bot_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: